### PR TITLE
Set GenStage as not optional

### PR DESCRIPTION
**Pull request by luisguilhermemsalmeida**
Issue https://github.com/malomohq/shopify-graphql-elixir/issues/24

### CODE REVIEW

**Comment by luisguilhermemsalmeida** [comment]
@anthonator I don't understand why GenStage was set as optional, I just removed that tag? Does that make sense to you?

Also, I would need a branch to be created based on the 1.6.0 tag, since I would merge on that branch and a release would be created from there, right?

**Comment by anthonator** [comment]
Thanks for reporting this issue.

I don't think removing `gen_stage` as an optional dependency is a good solution here.

I pushed some code to ensure the limiter modules aren't compiled if `gen_stage` is not present.

The update is in `2.0.0-rc.1`. Would you be willing to give that a shot?

**Comment by luisguilhermemsalmeida** [comment]
It seems to be working fine!
I'll confirm it in a moment

**Comment by luisguilhermemsalmeida** [comment]
All working good! thanks! I'll close this PR

**Pull request closed without merging**
